apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 80  # Port to expose
      targetPort: 8080  # Port where your app is running inside the container
  type: LoadBalancer  # This creates a LoadBalancer service