name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: your-region

      - name: Build Docker image
        run: docker build -t your-image-name .

      - name: Tag Docker image
        run: docker tag your-image-name:latest your-account-id.dkr.ecr.your-region.amazonaws.com/your-repository-name:latest

      - name: Push Docker image to ECR
        run: docker push your-account-id.dkr.ecr.your-region.amazonaws.com/your-repository-name:latest
