name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 235494784214.dkr.ecr.us-east-1.amazonaws.com

      - name: Set up JDK 24
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '24'

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker image
        run: docker build -t awslearn1 .

      - name: Tag Docker image
        run: docker tag awslearn1:latest 235494784214.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repo:latest

      - name: Push Docker image to ECR
        run: docker push 235494784214.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repo:latest