name: Terraform ECR and EKS Management
 
on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action to perform (create or destroy)"
        required: true
        default: "create"
        type: choice
        options:
          - create
          - destroy
 
env:
  AWS_REGION: "us-east-1"  # Replace with your preferred region
 
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
 
      - name: Terraform Init
        run: terraform init
        working-directory: Infra/Terraform
 
      - name: Terraform Apply (Create)
        if: ${{ github.event.inputs.action == 'create' }}
        run: terraform apply -auto-approve
        working-directory: Infra/Terraform
 
      - name: Terraform Destroy (Destroy)
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: terraform destroy -auto-approve
        working-directory: Infra/Terraform